/*
 * Wish Tally - Conversion
 * Version 1.5 made by yippym
 */

// Wish Tally Const
var WISH_TALLY_CHARACTER_EVENT_WISH_SHEET_NAME = "Character Event Wish History";
var WISH_TALLY_WEAPON_EVENT_WISH_SHEET_NAME = "Weapon Event Wish History";
var WISH_TALLY_PERMANENT_WISH_SHEET_NAME = "Permanent Wish History";
var WISH_TALLY_NOVICE_WISH_SHEET_NAME = "Novice Wish History";

var AUTO_IMPORT_SHEET_NAME = "Auto Import";

// Genshin Gacha
var GENSHIN_GACHA_EXPORT_SHEET_NAME = "genshin-gacha-export";
var GENSHIN_GACHA_CHARACTER_EVENT_WISH_SHEET_NAME = "Character Event Wish";
var GENSHIN_GACHA_WEAPON_EVENT_WISH_SHEET_NAME = "Weapon Event Wish";
var GENSHIN_GACHA_PERMANENT_WISH_SHEET_NAME = "Permanent Wish";
var GENSHIN_GACHA_NOVICE_WISH_SHEET_NAME = "Novice Wishes";

var GENSHIN_GACHA_EXPORT_SHEET_NAMES_FROM_FILE = {
  GENSHIN_GACHA_CHARACTER_EVENT_WISH_SHEET_NAME: WISH_TALLY_CHARACTER_EVENT_WISH_SHEET_NAME,
  GENSHIN_GACHA_WEAPON_EVENT_WISH_SHEET_NAME: WISH_TALLY_WEAPON_EVENT_WISH_SHEET_NAME,
  GENSHIN_GACHA_PERMANENT_WISH_SHEET_NAME: WISH_TALLY_PERMANENT_WISH_SHEET_NAME,
  GENSHIN_GACHA_NOVICE_WISH_SHEET_NAME: WISH_TALLY_NOVICE_WISH_SHEET_NAME
}

// Genshin Wishes
var GENSHIN_WISHES_EXPORT_SHEET_NAME = "genshin-wishes-export";
var GENSHIN_WISHES_CHARACTER_EVENT_WISH_SHEET_NAME = "Character Event";
var GENSHIN_WISHES_WEAPON_EVENT_WISH_SHEET_NAME = "Weapon Event";
var GENSHIN_WISHES_PERMANENT_WISH_SHEET_NAME = "Permanent";
var GENSHIN_WISHES_NOVICE_WISH_SHEET_NAME = "Novice";

// Ranges on sheet
var RANGE_EXPORT_FILE_TYPE = "C2";
var RANGE_EXPORT_GOOGLE_SHEET_TYPE = "C3";
var RANGE_FILE_TYPE_SELECTION = "A4";
var RANGE_FILE_URL_USER_INPUT = "A7";
var RANGE_WISH_TALLY_URL_USER_INPUT = "A10";

var RANGE_CHARACTER_EVENT_WISH_HISTORY_BANNER_SELECTION = "B13";
var RANGE_WEAPON_EVENT_WISH_HISTORY_BANNER_SELECTION = "B14";
var RANGE_PERMANENT_WISH_HISTORY_BANNER_SELECTION = "B15";
var RANGE_NOVICE_WISH_HISTORY_BANNER_SELECTION = "B16";
var RANGE_CHARACTER_EVENT_WISH_HISTORY = "B23";
var RANGE_WEAPON_EVENT_WISH_HISTORY = "B24";
var RANGE_PERMANENT_WISH_HISTORY = "B25";
var RANGE_NOVICE_WISH_HISTORY = "B26";
var RANGE_DATE_START = "B27";
var RANGE_DATE_END = "B28";

var RANGE_AUTO_IMPORT_STATUS_BY_BANNER_NAMES = {
  WISH_TALLY_CHARACTER_EVENT_WISH_SHEET_NAME: RANGE_CHARACTER_EVENT_WISH_HISTORY,
  WISH_TALLY_WEAPON_EVENT_WISH_SHEET_NAME: RANGE_WEAPON_EVENT_WISH_HISTORY,
  WISH_TALLY_PERMANENT_WISH_SHEET_NAME: RANGE_PERMANENT_WISH_HISTORY,
  WISH_TALLY_NOVICE_WISH_SHEET_NAME: RANGE_NOVICE_WISH_HISTORY
}

var RANGE_AUTO_IMPORT_SELECTION_BY_BANNER_NAMES = {
  WISH_TALLY_CHARACTER_EVENT_WISH_SHEET_NAME: RANGE_CHARACTER_EVENT_WISH_HISTORY_BANNER_SELECTION,
  WISH_TALLY_WEAPON_EVENT_WISH_SHEET_NAME: RANGE_WEAPON_EVENT_WISH_HISTORY_BANNER_SELECTION,
  WISH_TALLY_PERMANENT_WISH_SHEET_NAME: RANGE_PERMANENT_WISH_HISTORY_BANNER_SELECTION,
  WISH_TALLY_NOVICE_WISH_SHEET_NAME: RANGE_NOVICE_WISH_HISTORY_BANNER_SELECTION
}

var TEMP_SOURCE_TITLE = "GachaExport_WishTally_Conversion_Temp";